import { CollateNFTs } from "@/components/CollateNFTs";
import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import { NFT } from "nft-market";
import { useState } from "react";
import { Address, useContract, useContractRead, useContractReads, erc721ABI } from 'wagmi';

const NftCollection = () => {

    const [totalNFT, setTotalNFT] = useState<number>();
    const [NFTDetails, setNFTDetails] = useState<string[]>([]);
    const router = useRouter().query;
    const { contractAddress: NFTCollectionAddress } = router;
    useContractRead({
        address: NFTCollectionAddress as Address,
        abi: erc721ABI,
        functionName: 'totalSupply',
        onSuccess(data) {
            setTotalNFT(Number(data));
        }
    })

    useContractReads({
        contracts: [
            {
                address: NFTCollectionAddress as Address,
                abi: erc721ABI,
                functionName: 'name',
            },
            {
                address: NFTCollectionAddress as Address,
                abi: erc721ABI,
                functionName: 'symbol',
            }
        ],
        onSuccess(data) {
            setNFTDetails(data);
        },
    })

    return (
        <>
            <Head>
                <title>NFT Marketplace</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <div className=" rounded-lg bg-slate-100 px-6 py-4 ring-1 ring-slate-700 flex justify-between items-center align-middle">
                    <h1 className="text-3xl font-semibold ">{NFTDetails[0]} <span className=" text-xs uppercase text-red-600 py-1 px-2 rounded-full ring-1 ring-red-800 bg-red-100">{NFTDetails[1]}</span></h1>
                <div>{NFTCollectionAddress}</div>
                </div>
                {/* <div>{totalNFT} </div> */}
                <div className="mt-10">
                    <CollateNFTs contractAddress={NFTCollectionAddress as Address} totalSupply={totalNFT ? totalNFT : 1} />
                </div>
            </main>
        </>
    );
};

export default NftCollection;