import Head from "next/head";
import Image from "next/image";
import { Address, useAccount, useBalance } from "wagmi";
import { ContractContext } from "./_app";
import { Context, useContext, useEffect, useState } from "react";

const Home = () => {

  const NFT_Contract = useContext(ContractContext);

  return (
    <>
      <Head>
        <title>NFT Marketplace</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>{NFT_Contract}</div>
      </main>
    </>
  );
};

export default Home;
